packaging_format = 2

id = "2fauth"
name = "2FAuth"
description.en = "self-hosted alternative to One Time Passcode"
description.fr = "Alternative auto-hébergée a One Time Passcode"

version = "5.1.0~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
demo = "https://demo.2fauth.app/login"
admindoc = "https://docs.2fauth.app/"
code = "https://github.com/Bubka/2FAuth"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Bubka/2FAuth/archive/refs/tags/v5.1.0.tar.gz"
        sha256 = "fb811ab6567986c48d20358e7f24f099fa1c4cbc05982c47e40d94a3df121425"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "mariadb-server, php8.2-bcmath, php8.2-xml, php8.2-mbstring, php8.2-gd, php8.2-mysql, php8.2-curl"

    [resources.database]
    type = "mysql"
