packaging_format = 2

id = "2fauth"
name = "2FAuth"
description.en = "self-hosted alternative to One Time Passcode"
description.fr = "Alternative auto-hébergée a One Time Passcode"

version = "5.1.1~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0"
demo = "https://demo.2fauth.app/login"
admindoc = "https://docs.2fauth.app/"
code = "https://github.com/Bubka/2FAuth"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/Bubka/2FAuth/archive/refs/tags/v5.1.1.tar.gz"
        sha256 = "2e745b8770ae0bf38ae62a6d42f9f01d417cc36f03a02672b686bc7d155719e1"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.show_tile = false
    api.allowed = "visitors"
    api.auth_header = false

    [resources.apt]
    packages = "mariadb-server, php8.2-bcmath, php8.2-xml, php8.2-mbstring, php8.2-gd, php8.2-mysql, php8.2-curl"

    [resources.database]
    type = "mysql"
